name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn package

      - name: Login to Docker registry (if pushing)
        if: patricedjate8@gmail.com
        uses: docker/login-action@v2
        with:
          username: patricedjate8@gmail.com
          password: Djtp@0768

      - name: Build Docker image
        run: docker build -t my-spring-boot-app:latest .

      - name: Push Docker image (if pushing)
        if: patricedjate8@gmail.com
        run: docker push my-spring-boot-app:latest
